### ISSUE TITLE
`ms-vscode.mock-debug` is mysteriously missing

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#1444]
The extension is published from https://github.com/open-vsx/publish-extensions and in the logs, the extension is reportedly being published successfully, but when going to request it from https://open-vsx.org, it gives a 404 back. 

https://open-vsx.org/extension/ms-vscode/mock-debug
<img width="734" alt="image" src="https://user-images.githubusercontent.com/29888641/203854428-5c6bb8f4-a8ff-44f4-a833-baa43d3d1b5a.png">

**Comment by filiptronicek** [comment]
Logs: https://github.com/open-vsx/publish-extensions/actions/runs/3537480770/jobs/5937487121#step:9:5503

**Comment by kineticsquid** [comment]
@filiptronicek I scanned the build log file about and found 9 instances of this `Error: Namespace already exists:` error. Of those 9 instances, and despite the fact the that log reports that the extensions were published, the following extensions do not show up in the registry:
```
Error: Namespace already exists: Dannark
https://open-vsx.org/extension/Dannark/AndroidLauncher
Error: Namespace already exists: ms-pyright
https://open-vsx.org/extension/ms-pyright/vscode-pyright
Error: Namespace already exists: ms-vscode
https://open-vsx.org/extension/ms-vscode/mock-debug
Error: Namespace already exists: vscjava
https://open-vsx.org/extension/vscjava/vscode-gradle
Error: Namespace already exists: Vue
https://open-vsx.org/extension/Vue/vscode-typescript-vue-plugin
```

While these extensions do show up in the registry:
```
Error: Namespace already exists: amazonwebservices
https://open-vsx.org/extension/amazonwebservices/aws-toolkit-vscode
Error: Namespace already exists: maziac
https://open-vsx.org/extension/maziac/asm-code-lens
Error: Namespace already exists: mrorz
https://open-vsx.org/extension/mrorz/language-gettext
Error: Namespace already exists: ms-vscode
https://open-vsx.org/extension/ms-vscode/cpptools-themes
```

I cannot find a pattern.

**Comment by kineticsquid** [comment]
@filiptronicek @amvanbaren I poked around a bit more with this one. I have a gitpod workspace with an open-vsx deployment. I built this extension there to get a `.vsix` file with yarn install, build, package. I then published that with the 'Publish' link. It published successfully and I could see it in the catalog. 

As an aside, similar to `ms-pyright.vscode-pyright` in #1532, from the admin panel, while I can list the extension by publisher and by namespace, when I attempt to list the extension with the 'Extension' link on the admin panel by specifying the namespace and the extension name, the page spins and never returns.

**Comment by filiptronicek** [comment]
Looks like this is indeed not the case anymore, thanks for the ping.

**Comment by filiptronicek** [comment]
It looks like the same is happening again now with `vscjava.vscode-gradle`. @kineticsquid could you check and if possible, publish the `.vsix` from https://github.com/microsoft/vscode-gradle/releases/tag/3.12.7?

**Comment by kineticsquid** [comment]
@filiptronicek When I poked into this back in [November](https://github.com/EclipseFdn/open-vsx.org/issues/1444#issuecomment-1329952090), this was one of the extensions that was not showing up, like `ms-vscode.mock-debug`. Did it mysteriously show up between then and now?

**Comment by kineticsquid** [comment]
@filiptronicek I can publish the extension, but only by adding myself to the workspace.

**Comment by filiptronicek** [comment]
> @kineticsquid: Did it mysteriously show up between then and now?

I don't know... I... think so? I kind of want to believe that I would notice it missing for more than a couple weeks at a time, but maybe it just slipped through my radar. It might've, but I'm assuming it hasn't.

> I can publish the extension, but only by adding myself to the workspace.

Since it's our namespace, I think there is no problem doing that. If you find the time I would appreciate if you tried

**Comment by kineticsquid** [comment]
@filiptronicek I added myself as a contributor to the `vscjava` namespace. I attempted to publish the `.vsix` file from the 3.12.7 release I received the following error:
<img width="505" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/9470913d-3f00-44dd-a671-38abedea5a48">

Was that build OK?

**Comment by kineticsquid** [comment]
@filiptronicek ^^^^

**Comment by filiptronicek** [comment]
@kineticsquid that's weird. Could you try using `ovsx` to publish from your local terminal? The `.vsix` I shared should be alright: I installed it in a fresh VS Code installation and it seemed to do what it should.

**Comment by kineticsquid** [comment]
@filiptronicek I tried the following:
```
npx ovsx publish vscjava.vscode-gradle-3.12.7.vsix -p xxxxxxxxxxxxxxx
```

Result:
```
❌  Internal Server Error
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
johnkellerman@Johns-MBP Downloads % 

```

**Comment by kineticsquid** [comment]
@filiptronicek ^^^^

**Comment by kineticsquid** [comment]
@filiptronicek ^^^^

**Comment by filiptronicek** [comment]
Sorry for the delay, @kineticsquid and thanks for posting the outputs of your publishing. Since this is one of the mysterious server errors, could you @amvanbaren look into server logs to see what could be up? 🙏 

Interesting to note that we get a different error than the one from the Web UI as well, but I think that's just an issue with the web uploader.

**Comment by kineticsquid** [comment]
@filiptronicek Thanks for getting back to me. I just re-published the extension to the same result.

@amvanbaren This error was at 19:27 CEST. Can you take a look at the logs?

**Comment by amvanbaren** [comment]
At 19:27 CEST I found:
```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_extension_public_id"
  Detail: Key (public_id)=(a226f06e-9b5e-493b-b92a-553d3572f969) already exists.
```

**Comment by filiptronicek** [comment]
@amvanbaren I assume that means that the extension version has already been published?

**Comment by kineticsquid** [comment]
I think this is resolved now. @filiptronicek?

**Comment by filiptronicek** [comment]
@kineticsquid this is indeed resolved for mock-debug, but seems to still be the case for [Gradle](https://open-vsx.org/extension/vscjava/vscode-gradle) and [GitHub Actions](https://open-vsx.org/extension/GitHub/vscode-github-actions)...

**Comment by kineticsquid** [comment]
@filiptronicek I'm looking at the latest log, https://github.com/open-vsx/publish-extensions/actions/runs/5527236818, and it indicates that neither of these were published. TBH, I don't recall this overview view of the auto-publishing results.

**Comment by filiptronicek** [comment]
@kineticsquid see [line 1933](https://github.com/open-vsx/publish-extensions/actions/runs/5527236818/jobs/10082792119#step:10:1936) of the `node publish extensions` step:
> Published GitHub.vscode-github-actions to https://open-vsx.org/extension/GitHub/vscode-github-actions

**Comment by kineticsquid** [comment]
@filiptronicek Thanks. I went through the log file again, looking for all instances of `Error: Namespace already exists:`. I found the following six extensions. The first three were not published. The second three were. 
```
Published Dannark.AndroidLauncher to https://open-vsx.org/extension/Dannark/AndroidLauncher
Published GitHub.vscode-github-actions to https://open-vsx.org/extension/GitHub/vscode-github-actions
Published vscjava.vscode-gradle to https://open-vsx.org/extension/vscjava/vscode-gradle

Published mrorz.language-gettext to https://open-vsx.org/extension/mrorz/language-gettext
Published MS-CEINTL.vscode-language-pack-pt-BR to https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-pt-BR
Published ms-vscode.cpptools-themes to https://open-vsx.org/extension/ms-vscode/cpptools-themes
```

I cloned repos for each of the three extensions not published and attempted to package locally and publish with `vsce package` and `npx ovsx publish`. 
- `Dannark/AndroidLauncher`:
Publishing fails because there is no 'license.txt' file.
- `GitHub/vscode-github-actions`
Packaging fails because the extensions name, `@github/vscode-github-actions` is invalid.
- `vscjava/vscode-gradle`
Packaging fails because the repo has no `package.json` file.

This is a bit strange since the log messages clearly indicate these three extensions were published.

**Comment by kineticsquid** [comment]
@filiptronicek Thanks, this is helpful for me to understand the processing. In looking through the log file from the action run above, for when we decide we need to update an extension, it looks like in some cases we build it and in other cases, we just get the `.vsix` file and install it. How do we make that decision? I did poke a bit at `publish-extensions.js` and `publish-extension.js`, but JavaScript is not in my repertoire.

**Comment by filiptronicek** [comment]
@kineticsquid we would love to "just get the `.vsix`" every time, so we try to do that. Not all extensions publish to GitHub Releases, though, so manual building is necessary.

**Comment by kineticsquid** [comment]
@filiptronicek I took another swing at this. I added myself as a contributor to the namespace of both of these extensions:
```
https://open-vsx.org/extension/GitHub/vscode-github-actions
https://open-vsx.org/extension/vscjava/vscode-gradle
```

Used `npx osvx publish ... --debug` to attempt to publish, with the following results:
```
johnkellerman@Johns-MBP temp % npx ovsx publish vscjava.vscode-gradle-3.12.7.vsix -p ********* --debug
Error: Internal Server Error
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ovsx/lib/registry.js:176:40)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
johnkellerman@Johns-MBP temp % npx ovsx publish vscode-github-actions-0.25.8.vsix -p ********* --debug
Error: Internal Server Error
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ovsx/lib/registry.js:176:40)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
johnkellerman@Johns-MBP temp % 
```
Just prior to this I published a simple extension of mine successfully. 

@amvanbaren this was at approx 20:00 CEST today, July 25. Is there anything useful in the logs?

**Comment by kineticsquid** [comment]
One more observation. I fired up a Gitpod deployment based on the most recent code at openvsx. I was able to publish the above two `.vsix` files successfully.

**Comment by amvanbaren** [comment]
The public_id already exists in the database.

**Comment by kineticsquid** [comment]
@amvanbaren When I search for both of these extensions on the admin panel, which also shows deactivated extensions, it says they don't exist. Do we need some DB surgery here?

**Comment by amvanbaren** [comment]
@kineticsquid No, the call to the `/publish` endpoint failed. There's no extension version in the database. 
I think this can be fixed by a daily job that checks if all public ids are up-to-date.

**Comment by kineticsquid** [comment]
@amvanbaren How long has that job been running, this issue seems to have been around for some time.

**Comment by amvanbaren** [comment]
currently there is no job

**Comment by amvanbaren** [comment]
@kineticsquid Yes, a daily job or whenever a new extension is published. Maybe even both.

**Comment by amvanbaren** [comment]
I think that the `publicId` stays the same when a publisher changes their namespace name or extension name on the VS Marketplace, whereas in Open VSX a new namespace or extension has to be created when the name changes. 

For example:
- Publisher has an extension on the VS Marketplace named `foo` with public id `123`
- Publisher publishes `foo` to Open VSX, its public id is also `123` (got it from the VS Marketplace)
- Publisher changes the extension name from `foo` to `bar` on the VS Marketplace, its public id is still `123`
- Publisher tries to publish `bar` to Open VSX, it fails because `foo` still has public id `123` (it was never updated)

**Comment by kineticsquid** [comment]
I can see `publicId` in the `extension` table. It's not visible externally, right? Is it correct that this happens only with an extension that has a name change and is auto-published?

**Comment by amvanbaren** [comment]
> It's not visible externally, right?

It is included in the `/extensionquery` endpoint response.

> Could we fix this by unpublishing these missing extensions

I guess you can, but it's a common problem that over time will return.

**Comment by kineticsquid** [comment]
Why is this only an issue with auto-published extensions? Or is it? 

Can we provide guidance to the publishers for how to do this name change at the VS registry without running into issues here?

**Comment by kineticsquid** [comment]
@filiptronicek On my admin panel, I can see extensions that are published but not active. I don't see `8.100`, the most recent I see, which matches the extension detail page, is `7.100`.

**Comment by kineticsquid** [comment]
@filiptronicek @amvanbaren Are we good to close this one?

**Comment by kineticsquid** [comment]
@filiptronicek @amvanbaren ^^^^

**Comment by amvanbaren** [comment]
@kineticsquid Let's wait until v0.14.2 is running on open-vsx.org. It will contain https://github.com/eclipse/openvsx/pull/822

**Comment by amvanbaren** [comment]
The `public_id` update job has been deployed for 2 weeks. There are no more `public_id` unique constraint violations in the logs. Only [vscjava.vscode-gradle](https://open-vsx.org/extension/vscjava/vscode-gradle) isn't showing up.

**Comment by kineticsquid** [comment]
@amvanbaren Yeah, the auto-publishing is failing for this: https://github.com/open-vsx/publish-extensions/actions/runs/7881268679/job/21504618286#step:12:7401.

I manually published the latest version: https://open-vsx.org/extension/vscjava/vscode-gradle.
