### ISSUE TITLE
oderwat.indent-rainbow-8.0.0.vsix package seems corrupted

### ISSUE THREAD

**Issue by Tyf0x** [EclipseFdn/open-vsx.org#674]
When installed in vscodium, this package fails with the following errors:

```
[2021-09-17 23:36:53.979] [exthost] [error] Activating extension oderwat.indent-rainbow failed due to an error:
[2021-09-17 23:36:53.979] [exthost] [error] Error: Cannot find module 'c:\Users\[redacted]\.vscode-oss\extensions\oderwat.indent-rainbow-8.0.0\out\extension'
Require stack:
- c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js
- c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\bootstrap-amd.js
- c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
	at Module._load (internal/modules/cjs/loader.js:732:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:28190)
	at Function.E._load (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:24778)
	at Function.o._load (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:59872)
	at Module.require (internal/modules/cjs/loader.js:959:19)
	at Module.require (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\extensions\typescript-language-features\dist\extension.js:1:48233)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:5:101)
	at v._loadCommonJSModule (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:26187)
	at v._doActivateExtension (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12594)
	at v._activateExtension (c:\Users\[redacted]\AppData\Local\Programs\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:11695)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 8)
	at async Promise.all (index 0)
```

Installing the extension for the vsix from the MS marketplace works as expected.

**Comment by brianking** [comment]
@spoenemann Does this look like a publishing / registry issue, or an issue with the individual extension?

**Comment by Tyf0x** [comment]
If that's of any help, it seems the open-vsx version is missing critical files (see screenshot)

![image](https://user-images.githubusercontent.com/6980921/134276178-f7fce21a-59f2-4ef2-b63e-f7b351395a04.png)

**Comment by spoenemann** [comment]
> Cannot find module '...\oderwat.indent-rainbow-8.0.0\out\extension'

Most likely a build step was missed when publishing the extension.

**Comment by brianking** [comment]
It looks like this should be filed as an issue in the repository of the extension (i.e. taken up with the publisher). If I am wrong, feel free to reopen.
